@echo off
echo Starting Osiris Trading System...

echo Starting MT5 Trading Engine...
start cmd /k "python main.py"

echo Starting FastAPI Backend...
start cmd /k "python -m uvicorn api.server:app --host 127.0.0.1 --port 8000"

echo Starting Next.js Dashboard (Production)...
start cmd /k "cd frontend && npm start"

echo Waiting for services to initialize...
timeout /t 5 /nobreak > nul

echo Opening Dashboard...
start http://localhost:3000
pause
