@echo off
echo Starting Osiris Trading System (Dev Mode)...

echo Starting MT5 Trading Engine...
start cmd /k "python main.py"

echo Starting FastAPI Backend...
start cmd /k "python -m uvicorn api.server:app --reload --host 0.0.0.0 --port 8000"

echo Starting Next.js Dashboard (Dev)...
start cmd /k "cd frontend && npm run dev"

echo Waiting for services to initialize...
timeout /t 5 /nobreak > nul

echo Opening Dashboard...
start http://localhost:3000
pause
